web/router.ex
defmodule ResearchResource.Router do
  use ResearchResource.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ResearchResource.Auth, repo: ResearchResource.Repo
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", ResearchResource do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", AboutController, :index
    # /about/consent is used to display the about page after a user signup, see #106
    get "/about/consent", AboutController, :about
    get "/about/download", AboutController, :download
    get "/consent/view", ConsentController, :view
    get "/consent/confirm", ConsentController, :confirm
    get "/who", WhoWeAreController, :index
    get "/faqs", FaqsController, :index
    get "/terms_and_conditions", TsAndCsController, :index
    get "/resources", ResourcesController, :index

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/users", UserController, only: [:show, :new, :create]
    resources "/consent", ConsentController, only: [:new, :create]
    resources "/qualtrics", QualtricsController, only: [:new]
    resources "/projects", ProjectsController, only: [:index, :show, :create]
    resources "/account", AccountController, only: [:index, :update]
    resources "/change_password", ChangePasswordController, only: [:index, :update]
    resources "/contact", ContactController, only: [:index, :create]
  end
end

web/controllers/consent_controller.ex
defmodule ResearchResource.ConsentController do
  use ResearchResource.Web, :controller

  alias ResearchResource.{Redcap.RedcapHelpers, Qualtrics.QualtricsHelpers,
                          User, Email, Mailer}

  plug :authenticate_user when action in [:new, :create, :view, :confirm]

  @redcap_api Application.get_env(:research_resource, :redcap_api)
  @qualtrics_api Application.get_env(:research_resource, :qualtrics_api)
  @contact_email Application.get_env(:research_resource, :contact_email)

  def new(conn, _params) do
    case conn.assigns.current_user.ttrr_consent do
      true ->
        redirect(conn, to: consent_path(conn, :view))
      _ ->
        render(conn, "new.html", consent_questions: @redcap_api.get_instrument_fields("consent"))
    end
  end

  # save user and consent
  def create(conn, %{"consent" => consent}) do
    case check_consent(consent) do
      true ->
        conn
        |> create_user_redcap(consent)
        |> update_consent
        |> create_user_qualtrics
        |> send_saliva_email(consent)
        |> case do
          {:ok, :sent} ->
            redirect(conn, to: consent_path(conn, :confirm))
          {:ok, :not_sent} ->
            redirect(conn, to: qualtrics_path(conn, :new))
        end
      false ->
        conn
        |> put_flash(:error, "You must consent to the required questions")
        |> redirect(to: consent_path(conn, :new))
    end
  end

  # redirect to the consent page if the form is submitted without any values (consent map is not defined)
  def create(conn, _) do
    redirect(conn, to: consent_path(conn, :new))
  end

  def create_user_redcap(conn, consent) do
    user_data = RedcapHelpers.user_to_record(conn.assigns.current_user)

    consent
    |> Enum.filter(fn {key, _} -> String.starts_with?(key, "consent") end)
    |> RedcapHelpers.consent_to_record
    |> Map.merge(user_data)
    |> Map.merge(%{user_details_complete: 2, consent_complete: 2})
    |> @redcap_api.save_record

    conn
  end

  def create_user_qualtrics(conn) do
    contact_qualtrics = QualtricsHelpers.user_to_qualtrics_contact(conn.assigns.current_user)

    case @qualtrics_api.create_contact(contact_qualtrics) do
      {:ok, id} ->
        # update user model and postgres data with qualtrics id
        changeset = User.changeset(conn.assigns.current_user, %{"qualtrics_id" => id})
        case Repo.update(changeset) do
          {:ok, user} ->
            conn
            |> assign(:current_user, user)
        end
    end
  end

  defp check_consent(consent) do
    Enum.all?(consent, fn {k, v} ->
      if String.starts_with?(k, "consent") and String.last(k) == "y" do
        v == "Yes"
      else
        true
      end
    end)
  end

  def view(conn, _params) do
    render(conn, "view.html",
      consent_questions: @redcap_api.get_instrument_fields("consent"),
      consent_answers: @redcap_api.get_user_data(conn.assigns.current_user.ttrrid)
    )
  end

  def update_consent(conn) do
    changeset = User.changeset(conn.assigns.current_user, %{"ttrr_consent" => true})

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> assign(:current_user, user)
    end
  end

  def send_saliva_email(_conn, user_details) do
    if (Map.has_key?(user_details, "name") and
      Map.has_key?(user_details, "address_1") and
      user_details["name"] != "" and
      user_details["address_1"] != ""
    ) do
      subject = "Saliva Kit Requested"
      message = "The following user has requested a saliva kit:\n
      Name: #{user_details["name"]}\n
      Address:
      #{user_details["address_1"]}
      #{user_details["address_2"]}
      #{user_details["town"]}
      #{user_details["county"]}
      #{user_details["postcode"]}"

      @contact_email
      |> Email.send_email(subject, message)
      |> Mailer.deliver_now()

      {:ok, :sent}
    else
      {:ok, :not_sent}
    end
  end

  def confirm(conn, _params) do
    render conn, "confirm.html"
  end
end

web/views/consent_view.ex
defmodule ResearchResource.ConsentView do
  use ResearchResource.Web, :view
end

web/templates/consent/confirm.html.eex
<div class="montreal dark-blue">
  <div class="pa4 w-60-ns dib">
    <p>
      Thank you for requesting your saliva sample kit, you should receive it in the post shortly
    </p>
    <div class="pt4">
      <%= link "Continue", to: "/qualtrics/new", class: "montreal-bold db w5 tc mr3 ba bw1 f16 link br-pill ph3 pv2 mb2 white bg-green hover-bg-white b--green hover-green pointer ttu" %>
    </div>
  </div>
</div>

web/templates/consent/index.html.eex
<div class="pa4 w-60">
  <h2>Welcome To Research Resource, <%=String.capitalize @current_user.first_name%></h2>
  <p>
    In order to complete your registration, there are a few more things that we need to ask of you.
  </p>
  <p>
    You will need to complete an initial questionnaire, and follow up questionnaires once a year. A link for these will be emailed to you.
  </p>
  <p>
    Additionally, consent needs to be given for a number of different things. Please complete this below, and don't hesitate to get in touch if you need more information.
  </p>
</div>

<div class="pa4 w-60">
  <h3>Consent</h3>
  <p>
    Talking Therapies Research Resource in collaboration with the SLaM NIHR BioResource for Mental Health.
  </p>
  <p>
    Name of Principal Investigators:
    Prof. Thalia Eley and Dr Gerome Breen
  </p>
</div>

<div class="pa4">
  <div class="dib w-50 v-mid mr5">
    <p>
      The following points are about signing up to the Talking Therapies Research Resource, access to treatment records and taking part in research projects.
    </p>
    <p>
      Please watch our animation about consent if you need more information.
    </p>
    <p>
      You must answer "Yes" or "No" to each question in order to sign up to the register.
    </p>
  </div>
  <div class="dib h5 w-40 outline v-mid tc">
    <h5>Watch Animation on Consent</h5>
  </div>
</div>

<%= for { question, i } <- Enum.with_index @consent_questions do %>
  <div class="<%= get_background_colour(i) %> pa4">
    <span class="ph5"><%= i + 1 %>.</span>
    <div>
      <div class="dib v-mid w-80 mr2 ph5">
        <p>
          <%= question["field_label"] %>
        </p>
      </div>
      <div class="dib v-mid">
        <%= radio_button question["form name"], question["field_name"], "Yes"%>
        <%= label question["form name"], question["field_name"], "Yes" %>
        <%= radio_button question["form name"], question["field_name"], "No" %>
        <%= label question["form name"], question["field_name"], "No" %>
      </div>
    </div>
  </div>
<% end %>

<div class="pa3 ph5">
  <%= submit "Next", class: "mr3 bn f6 link dim br-pill ph3 pv2 mb2 dib white bg-blue" %>
  <%= link "Cancel", to: "#", class: "dib" %>
</div>

web/templates/consent/new.html.eex
<div class="montreal dark-blue">
  <div class="pa4 w-60-ns dib">
    <h2>GENERAL ADULT CONSENT FORM</h2>
    <h3>Name of Principal Investigators: Prof. Thalia Eley and Dr Gerome Breen</h3>
    <p>
      The Talking Therapies Research Resource (TTRR) is a branch of the SLaM NIHR BioResource for Mental Health. It is a way for those who have received a talking therapy within IAPT to participate in research aimed at understanding how these treatments work and the causes of anxiety and depression. Within the BioResource, the Talking Therapies Research Resource team is responsible for the project.
    </p>
  </div>

  <div class="dib-ns dn w-30 v-mid">
    <div class="w-90 db-ns dn center">
      <%= component "request_call", conn: @conn %>
    </div>
  </div>

  <h3 class="ph5">Consent items for the Talking Therapies Research Resource</h3>
  <%= form_for @conn, consent_path(@conn, :create), [as: :consent], fn f -> %>
  <%= for { question, i } <- Enum.with_index @consent_questions do %>
  <%= component "consent_question", question: question, i: i, f: f %>
  <% end %>
  <div class="pa4 bg-light-blue">
    <div class="dib v-mid ph5-ns">
      <h3>Please provide your details so that we can send you a saliva kit.</h3>
      <span>You should receive it in the post shortly.</span>
      <div class="w-40-ns mt4">
        <%= text_input f, :name, placeholder: "Name", class: "ba br2 pa2 montreal tracked dark-blue w-70 mb2" %>
        <%= text_input f, :postcode, placeholder: "Postcode", class: "ba br2 pa2 montreal tracked dark-blue w-70 mb2" %>
        <%= text_input f, :address_1, placeholder: "Address Line 1", class: "ba br2 pa2 montreal tracked dark-blue w-70 mb2" %>
        <%= text_input f, :address_2, placeholder: "Address Line 2", class: "ba br2 pa2 montreal tracked dark-blue w-70 mb2" %>
        <%= text_input f, :town, placeholder: "Town/City", class: "ba br2 pa2 montreal tracked dark-blue w-70 mb2" %>
        <%= text_input f, :county, placeholder: "County", class: "ba br2 pa2 montreal tracked dark-blue w-70 mb2" %>
      </div>
    </div>
  </div>
  <div class="ph4">
    <div class="mt3 ph5-ns">
      <%= component "button_ok", class: "dn", value: "Next", id: "next-active" %>
      <%= component "button_error", class: nil, value: "You cannot complete registration", id: "next-inactive" %>
    </div>
  </div>
  <% end %>
</div>

web/templates/consent/view.html.eex
<div class="mw9 center ph5-ns ph4 pt4 montreal dark-blue">
  <div class="dib w-60-ns v-mid pa2-ns">
    <h2>Hi, <%= @current_user.first_name %></h2>
    <p>
      These are the items you have consented to:
    </p>
  </div>
</div>

<%= for { question, i } <- Enum.with_index @consent_questions do %>
  <%= component "consent_question", question: question, i: i, consent_answers: @consent_answers %>
<% end %>

<div class="montreal dark-blue bg-lightest-blue ph5 pv3">
  <p>
    If you wish to withdraw your consent from any of the above items, please contact the team:
  </p>
  <div class="pv1">
    <p>
      Call us for free: 0800 955 199
    </p>
    <p>
      Email us: <a href="mailto:ttrr@kcl.ac.uk">ttrr@kcl.ac.uk</a>
    </p>
    <p>
      <%= link "Read the FAQs", to: faqs_path(@conn, :index) %>
    </p>
  </div>
  <div class="pv2">
    <h3 class="ttu">Request a Call Back</h3>
    <p>
      We aim to give you a call within 2 working days of your request.
    </p>
    <%= form_for @conn, contact_path(@conn, :create), [as: :callback], fn callback -> %>
      <div class="dib-ns w-20-ns">
        <%= label callback, :name, "Name", class: "db" %>
        <%= text_input callback, :name, class: "w-80 mb2 db ba br2 pa2 montreal tracked dark-blue" %>
      </div>
      <div class="dib-ns w-20-ns">
        <%= label callback, :time, "Best Time to Call", class: "db" %>
        <%= select callback, :time, ["Morning", "Afternoon", "Evening"], class: "w-80 mb2 db ba br2 pa2 montreal tracked dark-blue h2" %>
      </div>
      <div class="dib-ns w-20-ns">
        <%= label callback, :phone, "Phone Number", class: "db" %>
        <%= telephone_input callback, :phone, class: "w-80 mb4 mb2-ns db ba br2 pa2 montreal tracked dark-blue" %>
      </div>
      <div class="dib-ns">
        <%= component "button_ok", value: "Request Call back" %>
      </div>
    <% end %>
  </div>
</div>