web/router.ex
defmodule ResearchResource.Router do
  use ResearchResource.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ResearchResource.Auth, repo: ResearchResource.Repo
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", ResearchResource do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", AboutController, :index
    # /about/consent is used to display the about page after a user signup, see #106
    get "/about/consent", AboutController, :about
    get "/about/download", AboutController, :download
    get "/consent/view", ConsentController, :view
    get "/consent/confirm", ConsentController, :confirm
    get "/who", WhoWeAreController, :index
    get "/faqs", FaqsController, :index
    get "/terms_and_conditions", TsAndCsController, :index
    get "/resources", ResourcesController, :index

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/users", UserController, only: [:show, :new, :create]
    resources "/consent", ConsentController, only: [:new, :create]
    resources "/qualtrics", QualtricsController, only: [:new]
    resources "/projects", ProjectsController, only: [:index, :show, :create]
    resources "/account", AccountController, only: [:index, :update]
    resources "/change_password", ChangePasswordController, only: [:index, :update]
    resources "/contact", ContactController, only: [:index, :create]
  end
end

web/controllers/projects_controller.ex
defmodule ResearchResource.ProjectsController do
  use ResearchResource.Web, :controller

  alias ResearchResource.{Email, Mailer, Redcap.RedcapHelpers}

  @redcap_api Application.get_env(:research_resource, :redcap_api)
  @qualtrics_api Application.get_env(:research_resource, :qualtrics_api)
  @qualtrics_survey_id Application.get_env(:research_resource, :qualtrics_survey_id)

  def index(conn, _params) do
    projects = @redcap_api.get_projects()
    if conn.assigns.current_user do
      user_data = @redcap_api.get_user_data(conn.assigns.current_user.ttrrid)
      mine_other = %{
        mine: Enum.filter(projects, fn(project) -> complete?(user_data[project[:id_project] <> "_complete"]) end),
        other: Enum.filter(projects, fn(project) -> !complete?(user_data[project[:id_project] <> "_complete"]) end)
      }
      render conn, "index.html", projects: mine_other
    else
      current_archived = %{
        current: Enum.filter(projects, fn(project) -> project[:status] != "archived" end),
        archived: Enum.filter(projects, fn(project) -> project[:status] == "archived" end)
      }
      render conn, "index.html", projects: current_archived
    end
  end

  def show(conn, %{"id" => id_project}) do
    project = Map.merge(@redcap_api.get_project(id_project), %{applied: false})
    if conn.assigns.current_user do
      user_data = @redcap_api.get_user_data(conn.assigns.current_user.ttrrid)
      applied = %{applied: complete?(user_data[id_project <> "_complete"])}
      project = Map.merge(project, applied)
      consent_answers = user_data
      registration_complete = registration_complete?(conn.assigns.current_user)
      render conn, "show.html", project: project, consent_answers: consent_answers,
                                registration_complete: registration_complete
    else
      render conn, "show.html", project: project
    end
  end

  defp registration_complete?(user) do
    if user.ttrr_consent do
      {:ok, qualtics_contact} = @qualtrics_api.get_contact(user.qualtrics_id)
      response_survey =
        qualtics_contact["responseHistory"]
        |> Enum.find(&(&1["surveyId"] == @qualtrics_survey_id))
      response_survey["finishedSurvey"] && %{complete: true, step: nil} || %{commplete: false, step: "qualtrics"}
    else
      %{complete: false, step: "primary_consent"}
    end
  end

  def create(conn, %{"consent" => consent}) do
    user_data = RedcapHelpers.user_to_record(conn.assigns.current_user)
    complete_field = consent["id_project"] <> "_complete"

    consent
    |> Enum.filter(fn {key, _} -> String.starts_with?(key, "consent") end)
    |> RedcapHelpers.consent_to_record
    |> Map.merge(user_data)
    |> Map.merge(%{String.to_atom(complete_field) => 2})
    |> @redcap_api.save_record

    send_project_email(conn.assigns.current_user, consent["id_project"])

    conn
    |> put_flash(:info, "Thanks for consenting to the project!")
    |> redirect(to: projects_path(conn, :index))
  end

  defp complete?(value) do
    case value do
      "2" -> true
      _ -> false
    end
  end

  @contact_email Application.get_env(:research_resource, :contact_email)
  defp send_project_email(user, project) do
    subject = "New project application"
    message = """
    Hello,
    #{user.first_name} - #{user.ttrrid} has consented to the following project: #{project}
    """

    @contact_email
    |> Email.send_email(subject, message)
    |> Mailer.deliver_now()
  end

end

web/views/projects_view.ex
defmodule ResearchResource.ProjectsView do
  use ResearchResource.Web, :view

  def error_message_consent() do
    "If you do not consent to this option, you will not be able to join this project"
  end
end

web/templates/projects/index.html.eex
<div class="montreal dark-blue">
  <div class="mw9 center ph5-ns ph4 pv4">
    <div class="dib w-60-ns pa2-ns v-mid">
      <h2 class="ttu">Our Projects</h2>
      <p>
        Here are some examples of the research studies that members can take part in. Some of these studies are designed to give us a better understand of what treatments work for whom, and why. Others explore the characteristics of those for whom treatment has not worked, or have a broader goal around understanding what leads to the development of disorders such as anxiety and depression.
      </p>
      <p>
        As a member, you do not have to sign up to any of these studies if you do not want to, only those that interest you. Once you are signed in, you will be able to see further details about the research, and what would be expected of you as a participant.
      </p>
      <%= if !@current_user do %>
        <p>
          <%= link "Sign up now", to: user_path(@conn, :new) %> to become a member and start getting involved in research
        </p>
      <%= end %>
    </div>

    <%= if !@current_user do %>
      <%= component "sign_up_cta", conn: @conn %>
    <%= end %>
  </div>
  <%= if @current_user do %>
    <div class="mw9 pa5-ns pa4 bg-lightest-blue">
      <h3 class="ttu ph2">My Projects</h3>
      <p class="ph2">
        Projects you have consented to:
      </p>
      <div class="cf">
        <%= for project <- @projects[:mine] do %>
          <%= component "project", conn: @conn, project: project %>
        <% end %>
      </div>
    </div>

    <div class="mw9 pa5-ns pa4 bg-lightest-blue">
      <h3 class="ttu ph2">Other Projects</h3>
      <p class="ph2">
        Here are other projects that you can consent to:
      </p>
      <div class="cf">
        <%= for project <- @projects[:other] do %>
          <%= component "project", conn: @conn, project: project %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="mw9 pa5-ns pa4 bg-lightest-blue">
      <h3 class="ttu ph2">Current Projects</h3>
      <p class="ph2">
        These are projects that you can sign up to be a part of:
      </p>
      <div class="cf">
        <%= for project <- @projects[:current] do %>
          <%= component "project", conn: @conn, project: project %>
        <% end %>
      </div>
    </div>

    <div class="mw9 pa5-ns pa4 bg-lightest-blue">
      <h3 class="ttu ph2">Archived Projects</h3>
      <p class="ph2">
        These are projects that have already finished. You can find out about the results here:
      </p>
      <div class="cf">
        <%= for project <- @projects[:archived] do %>
          <%= component "project", conn: @conn, project: project %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

<%= if !@current_user do %>
  <%= component "sign_up", conn: @conn, current_user: @current_user %>
<% end %>

web/templates/projects/show.html.eex
<div class="montreal dark-blue">
  <div class="mw9 center ph5-ns ph4 pt4">
    <div class="dib w-60-ns pa2-ns v-mid">
      <h1> <%= @project[:name] %> </h1>
      <p>
        <%= @project[:description] %>
      </p>
    </div>

    <%= if @current_user do %>
      <%= if @registration_complete[:complete] do %>
        <%= if !@project[:applied] do %>
          <%= if @project[:status] != "archived" do %>
            <%= form_for @conn, projects_path(@conn, :create), [as: :consent], fn f -> %>
              <%= hidden_input f, :id_project, value: @project[:id_project] %>

              <%= for { question, i } <- Enum.with_index @project[:consents] do %>
                <%= component "consent_question", question: question, i: i, f: f , error_message: error_message_consent()%>
              <% end %>

              <div class="ph4-ns">
                <div class="pa3 ph5-ns">
                  <%= component "button_ok", class: "dn", value: "Apply", id: "next-active" %>
                  <%= component "button_error", class: nil, value: "You cannot complete application", id: "next-inactive" %>
                </div>
              </div>
            <% end %>
          <% end %>
        <%= else %>
          <%= for { question, i } <- Enum.with_index @project[:consents] do %>
            <%= component "consent_question", question: question, i: i, consent_answers: @consent_answers %>
          <% end %>
        <% end %>
      <% else %>
        <%= if @registration_complete[:step] == "primary_consent" do %>
          <p>
            You must complete the <%= link "Talking Therapies Research Resource consents", to: consent_path(@conn, :new) %> before you can consent to this project
          </p>
        <% end %>

        <%= if @registration_complete[:step] == "qualtrics" do %>
          <p>
            You must complete the <%= link "TTRR sign-up questionnaire", to: qualtrics_path(@conn, :new) %> before you can consent to this project
          </p>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>