web/router.ex
defmodule ResearchResource.Router do
  use ResearchResource.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ResearchResource.Auth, repo: ResearchResource.Repo
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", ResearchResource do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", AboutController, :index
    # /about/consent is used to display the about page after a user signup, see #106
    get "/about/consent", AboutController, :about
    get "/about/download", AboutController, :download
    get "/consent/view", ConsentController, :view
    get "/consent/confirm", ConsentController, :confirm
    get "/who", WhoWeAreController, :index
    get "/faqs", FaqsController, :index
    get "/terms_and_conditions", TsAndCsController, :index
    get "/resources", ResourcesController, :index

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/users", UserController, only: [:show, :new, :create]
    resources "/consent", ConsentController, only: [:new, :create]
    resources "/qualtrics", QualtricsController, only: [:new]
    resources "/projects", ProjectsController, only: [:index, :show, :create]
    resources "/account", AccountController, only: [:index, :update]
    resources "/change_password", ChangePasswordController, only: [:index, :update]
    resources "/contact", ContactController, only: [:index, :create]
  end
end

lib/research_resource/endpoint.ex
defmodule ResearchResource.Endpoint do
  use Phoenix.Endpoint, otp_app: :research_resource

  socket "/socket", ResearchResource.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :research_resource, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_research_resource_key",
    signing_salt: "yRdEWVBT"

  plug ResearchResource.Router
end

lib/research_resource/mailer.ex
defmodule ResearchResource.Mailer do
  use Bamboo.Mailer, otp_app: :research_resource
end

lib/research_resource/repo.ex
defmodule ResearchResource.Repo do
  use Ecto.Repo, otp_app: :research_resource
end

web/models/user.ex
defmodule ResearchResource.User do
  use ResearchResource.Web, :model

  alias Ecto.Changeset
  alias Comeonin.Bcrypt

  schema "users" do
    field :ttrrid, :string
    field :qualtrics_id, :string
    field :first_name, :string
    field :last_name, :string
    field :email, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    field :ttrr_consent, :boolean

    timestamps()
  end

  def changeset(model, params \\ :invalid) do
    model
    |> cast(params, ~w[first_name last_name email ttrrid qualtrics_id ttrr_consent])
    |> validate_required([:first_name, :last_name, :email])
    |> unique_constraint(:email)
  end

  def registration_changeset(model, params) do
    model
    |> changeset(params)
    |> cast(params, ~w(password))
    |> validate_required([:password])
    |> put_pass_hash()
  end

  def email_changeset(model, params \\ :invalid) do
    model
    |> cast(params, ~w(email))
    |> validate_required([:email])
    |> unique_constraint(:email)
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Bcrypt.hashpwsalt(pass))
      _ ->
        changeset
    end
  end
end

web/controllers/about_controller.ex
defmodule ResearchResource.AboutController do
  use ResearchResource.Web, :controller

  plug :authenticate_user when action in [:about]

  def index(conn, _params) do
    render conn, "index.html"
  end

  def about(conn, _params) do
    render conn, "about.html"
  end

  def download(conn, _params) do
    if (conn.assigns.current_user) do
      filename = Path.expand("web/static/assets/Information_Sheet_v9.180417_logged_in_user.pdf")
    else
      filename = Path.expand("web/static/assets/Information_Sheet_v9.180417_non_logged_in_user.pdf")
    end
    conn
    |> put_resp_header("content-disposition", ~s(attachment; filename="Information_Sheet.pdf"))
    |> send_file(200, filename)
  end
end

web/views/about_view.ex
defmodule ResearchResource.AboutView do
  use ResearchResource.Web, :view
end

web/views/account_view.ex
defmodule ResearchResource.AccountView do
  use ResearchResource.Web, :view
end

web/views/change_password_view.ex
defmodule ResearchResource.ChangePasswordView do
  use ResearchResource.Web, :view
end

web/views/component_view.ex
defmodule ResearchResource.ComponentView do
  use ResearchResource.Web, :view

  # Consent Question helpers
  def get_background_colour(index) when rem(index, 2) == 0, do: "bg-near-white"
  def get_background_colour(_index), do: "bg-white"

  def question_name(name, req) do
    case req do
      "y" ->
        String.to_atom("#{name}_y")
      "" ->
        String.to_atom("#{name}_n")
    end
  end

  def get_checked_yes(checked), do: checked == "1"

  def get_checked_no(checked), do: checked == "0"

  def truncate(text, limit_characters) do
    if String.length(text) < limit_characters do
      text
    else
      String.slice(text, 0..limit_characters) <> "..."
    end
  end
end

web/views/consent_view.ex
defmodule ResearchResource.ConsentView do
  use ResearchResource.Web, :view
end

web/views/contact_view.ex
defmodule ResearchResource.ContactView do
  use ResearchResource.Web, :view
end

web/views/error_view.ex
defmodule ResearchResource.ErrorView do
  use ResearchResource.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/faqs_view.ex
defmodule ResearchResource.FaqsView do
  use ResearchResource.Web, :view
end

web/views/layout_view.ex
defmodule ResearchResource.LayoutView do
  use ResearchResource.Web, :view
end

web/views/page_view.ex
defmodule ResearchResource.PageView do
  use ResearchResource.Web, :view
end

web/views/projects_view.ex
defmodule ResearchResource.ProjectsView do
  use ResearchResource.Web, :view

  def error_message_consent() do
    "If you do not consent to this option, you will not be able to join this project"
  end
end

web/views/qualtrics_view.ex
defmodule ResearchResource.QualtricsView do
  use ResearchResource.Web, :view
end

web/views/resources_view.ex
defmodule ResearchResource.ResourcesView do
  use ResearchResource.Web, :view
end

web/views/session_view.ex
defmodule ResearchResource.SessionView do
  use ResearchResource.Web, :view
end

web/views/ts_and_cs_view.ex
defmodule ResearchResource.TsAndCsView do
  use ResearchResource.Web, :view
end

web/views/user_view.ex
defmodule ResearchResource.UserView do
  use ResearchResource.Web, :view
end

web/views/who_we_are_view.ex
defmodule ResearchResource.WhoWeAreView do
  use ResearchResource.Web, :view
end

web/templates/about/about.html.eex
<%= component "about", conn: @conn, current_user: @current_user %>
<div class="pa3 ph5 mb4 mt2">
  <%= link "Next", to: "/consent/new", class: "db tc montreal-bold w5 mr3 ba bw1 f16 link br-pill ph3 pv2 mb2 white bg-green hover-bg-white b--green hover-green pointer ttu" %>
</div>
<%= render ResearchResource.AboutView, "request_call_footer.html", conn: @conn %>

web/templates/about/index.html.eex
<%= component "about", conn: @conn, current_user: @current_user, class: "montreal" %>
<%= if !@current_user do %>
  <div class="bg-white ph5-ns pt3 pb5 mw9 center" id="about-signup">
    <%= component "sign_up", conn: @conn, current_user: @current_user %>
  </div>
<% end %>
<%= render ResearchResource.AboutView, "request_call_footer.html", conn: @conn %>

web/templates/about/request_call_footer.html.eex
<div class="bg-lightest-blue pa4 montreal dark-blue" id="request-call-footer">
  <div class="w-100 db tc">
    <div class="bg-white dib w-30-ns w-90 center mb0-ns mb3 tl v-mid">
      <div class="bb b--lightest-blue pa3 ph4">
        <h4 class="dark-blue ma0">DOWNLOAD THE INFORMATION SHEET</h4>
      </div>
      <div class="pa3 ph4">
        <p>
          If you would like to download a PDF version of the Talking Therapies Research Resource Information Sheet, please click here
        </p>
        <%= link "DOWNLOAD", to: about_path(@conn, :download) %>
      </div>
    </div>
    <div class="ml5-ns bg-white dib w-50-ns w-90 center tl v-mid">
      <div class="bb b--lightest-blue pa3 ph4">
        <h4 class="dark-blue ma0">REQUEST A CALLBACK</h4>
      </div>
      <%= form_for @conn, contact_path(@conn, :create), [as: :callback], fn callback -> %>
        <div class="ph4">
          <p>
            We aim to give you a call within 2 working days of your request.
          </p>
          <div class="pv1">
            <div class="w-40-l dib-l">
              <%= label :callback, :name, "Name", class: "db" %>
              <%= text_input :callback, :name, class: "mb2 w-80 db ba br2 pa2 montreal tracked dark-blue" %>
            </div>
            <div class="w-40-l dib-l">
              <%= label :callback, :time, "Best Time to Call", class: "db" %>
              <%= select :callback, :time, ["Morning", "Afternoon", "Evening"], class: "mb2 w-80 db ba br2 montreal tracked dark-blue h2" %>
            </div>
          </div>
          <div class="w-40-l dib-l">
            <%= label :callback, :phone, "Phone Number", class: "db" %>
            <%= telephone_input :callback, :phone, class: "mb2 w-80 db ba br2 pa2 montreal tracked dark-blue" %>
          </div>
          <div class="w-40-ns dib-l">
            <%= component "button_ok", value: "Request Call back" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>